/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jokin_demo_ndkjni_FirstJni */

#ifndef _Included_com_jokin_demo_ndkjni_FirstJni
#define _Included_com_jokin_demo_ndkjni_FirstJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jokin_demo_ndkjni_FirstJni
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jokin_demo_ndkjni_FirstJni_get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
